<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */
function orbisius_ct_twentytwenty_child_theme_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_twentytwenty_child_theme_parent_style';
    $parent_base_dir = 'twentytwenty';

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        wp_get_theme( $parent_base_dir ) ? wp_get_theme( $parent_base_dir )->get('Version') : ''
    );

    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}
add_action('init','add_get_val');
function add_get_val() { 
    global $wp; 
    $wp->add_query_var('low'); 
}
add_action('init','add_get_val2');
function add_get_val2() { 
    global $wp; 
    $wp->add_query_var('num'); 
}
add_action('init','add_get_val3');
function add_get_val3() { 
    global $wp; 
    $wp->add_query_var('cap'); 
}
add_action( 'wp_enqueue_scripts', 'orbisius_ct_twentytwenty_child_theme_child_theme_enqueue_styles' );
remove_filter( 'the_content', 'wpautop' );
remove_filter( 'the_excerpt', 'wpautop' );